terminate called after throwing an instance of 'std::runtime_error'
  what():  Error| /home/aaron/Documents/Coding/cpp/LearnOpenGL-Vulkan/src/ImmediateSubmit.cpp:71 | VK_TIMEOUT
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error| /home/aaron/Documents/Coding/cpp/LearnOpenGL-Vulkan/src/ImmediateSubmit.cpp:71 | VK_ERROR_DEVICE_LOST
